server:
  port: 8091
spring:
  datasource:
    one:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource
    two:
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/test_lock?useSSL=false&serverTimezone=Asia/Shanghai
      type: com.alibaba.druid.pool.DruidDataSource